# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until "baseurl:"
  ...
email: beauinmelbourne@gmail.com
future: true # Include posts with a date in the future
github_username: explodinglabs
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
repository: explodinglabs/explodinglabs.github.io
social:
  name: Beau Barker
  links:
    - https://www.linkedin.com/in/beaub
    - https://github.com/explodinglabs
title: Beau Barker
url: "https://blog.explodinglabs.com" # the base hostname & protocol for your site
include: ['_pages']
