author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: A programming blog.
future: true # Include posts with a date in the future
github_username: explodinglabs
highlighter: rouge
locale: en_AU
markdown: kramdown
plugins:
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
repository: explodinglabs/composed.blog
social:
  name: Exploding Labs
  links:
    - https://github.com/explodinglabs
source: docs/
title: Composed
tagline: A programming blog
url: "https://composed.blog" # the base hostname & protocol for your site
whitelist:
  - jekyll-redirect-from
