# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: >
  A programming blog.
future: true # Include posts with a date in the future
gems:
    - github-pages
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
github_username: explodinglabs
highlighter: rouge
locale: en_AU
markdown: kramdown
# permalink: /:categories/:title
plugins:
    - github-pages
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
repository: explodinglabs/composed.blog
social:
  name: Exploding Labs
  links:
    - https://github.com/explodinglabs
source: docs/
title: Composed
tagline: A programming blog
url: "https://composed.blog" # the base hostname & protocol for your site
whitelist:
  - jekyll-redirect-from
  - jekyll-seo-tag
