# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: >
  A blog about programming, composition, Python and Haskell.
excerpt_separator: "<!--more-->"
future: true # Include posts with a date in the future
github_username: explodinglabs
highlighter: rouge
locale: en_AU
markdown: kramdown
permalink: /:categories/:title
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
repository: explodinglabs/explodinglabs.github.io
social:
  name: Exploding Labs
  links:
    - https://github.com/explodinglabs
title: Composed
tagline: A programming blog
url: "https://composed.blog/" # the base hostname & protocol for your site
include: ['_pages']
